---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---



    

## 網站資料爬取
```{r}
library(rvest)
ptt1<-"https://www.ptt.cc/bbs/movie/index.html"
pttcontent1<-read_html(ptt1)
post_title1<-pttcontent1%>%html_nodes(".title")%>%html_text()
post_title1
post_author1<-pttcontent1%>%html_nodes(".author")%>%html_text()
post_author1
post_good1<-pttcontent1%>%html_nodes(".nrec")%>%html_text()
post_good1

library(rvest)
html<-read_html("https://www.ptt.cc/bbs/movie/index.html")
btnurl<-html%>%html_nodes("a[class='btn wide']")%>%html_attr("href")
indexnum<-as.numeric(gsub("/bbs/movie/index|.html","",btnurl[2]))
for(i in(indexnum-3):(indexnum+1)){
  #print(i)
  print(paste0("https://www.ptt.cc/bbs/movie/index",i,",html"))
}


ptt2<-"https://www.ptt.cc/bbs/movie/index5279.html"
pttcontent2<-read_html(ptt2)
post_title2<-pttcontent2%>%html_nodes(".title")%>%html_text()
post_title2
post_author2<-pttcontent2%>%html_nodes(".author")%>%html_text()
post_author2
post_good2<-pttcontent2%>%html_nodes(".nrec")%>%html_text()
post_good2


ptt3<-"https://www.ptt.cc/bbs/movie/index5278.html"
pttcontent3<-read_html(ptt3)
post_title3<-pttcontent3%>%html_nodes(".title")%>%html_text()
post_title3
post_author3<-pttcontent3%>%html_nodes(".author")%>%html_text()
post_author3
post_good3<-pttcontent3%>%html_nodes(".nrec")%>%html_text()
post_good3

ptt4<-"https://www.ptt.cc/bbs/movie/index5277.html"
pttcontent4<-read_html(ptt4)
post_title4<-pttcontent4%>%html_nodes(".title")%>%html_text()
post_title4
post_author4<-pttcontent4%>%html_nodes(".author")%>%html_text()
post_author4
post_good4<-pttcontent4%>%html_nodes(".nrec")%>%html_text()
post_good4

ptt5<-"https://www.ptt.cc/bbs/movie/index5276.html"
pttcontent5<-read_html(ptt5)
post_title5<-pttcontent5%>%html_nodes(".title")%>%html_text()
post_title5
post_author5<-pttcontent5%>%html_nodes(".author")%>%html_text()
post_author5
post_good5<-pttcontent5%>%html_nodes(".nrec")%>%html_text()
post_good5

ptt6<-"https://www.ptt.cc/bbs/movie/index5275.html"
pttcontent6<-read_html(ptt6)
post_title6<-pttcontent6%>%html_nodes(".title")%>%html_text()
post_title6
post_author6<-pttcontent6%>%html_nodes(".author")%>%html_text()
post_author6
post_good6<-pttcontent6%>%html_nodes(".nrec")%>%html_text()
post_good6

ptt7<-"https://www.ptt.cc/bbs/movie/index5274.html"
pttcontent7<-read_html(ptt7)
post_title7<-pttcontent7%>%html_nodes(".title")%>%html_text()
post_title7
post_author7<-pttcontent7%>%html_nodes(".author")%>%html_text()
post_author7
post_good7<-pttcontent7%>%html_nodes(".nrec")%>%html_text()
post_good7



frame1<-data.frame(Title=c(post_title1),pushnum=c(post_good1),Author=c(post_author1))
frame1
frame2<-data.frame(Title=c(post_title2),pushnum=c(post_good2),Author=c(post_author2))
frame2
frame3<-data.frame(Title=c(post_title3),pushnum=c(post_good3),Author=c(post_author3))
frame3
frame4<-data.frame(Title=c(post_title4),pushnum=c(post_good4),Author=c(post_author4))
frame4
frame5<-data.frame(Title=c(post_title5),pushnum=c(post_good5),Author=c(post_author5))
frame5
frame6<-data.frame(Title=c(post_title6),pushnum=c(post_good6),Author=c(post_author6))
frame6
frame7<-data.frame(Title=c(post_title7),pushnum=c(post_good7),Author=c(post_author7))
frame7

dataframeAll<-rbind(frame1,frame2,frame3,frame4,frame5,frame6,frame7)
```

## 爬蟲結果呈現
```{r}
knitr::kable(dataframeAll[1:100,c("Title","pushnum","Author")])
```

## 解釋爬蟲結果 
```{r}
dim(dataframeAll)
```

抓出127筆觀察值，3個欄位

```{r}
table(dataframeAll$Author)
```

作者qpr322、iam168888888各有3篇po文

原來R的表格整理出來那麼好看啊!
